# Generated by Django 5.2.4 on 2025-07-10 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Yeni Ürün Bildirimi Gönderildi mi?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='playground.category', verbose_name='Kategorisi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Satışta mı?'),
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text='Örn: Bebek Mavisi, Fuşya', max_length=50, verbose_name='Renk Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bu Rengin Seri Fiyatı')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Bu renkten kaç seri stokta olduğunu belirtin.', verbose_name='Stok Adedi (Seri)')),
                ('is_main_color', models.BooleanField(default=False, help_text='Bu renk, ürün kartlarında gösterilecek. Her ürün için sadece BİR tane ana renk seçin.', verbose_name='Ana Renk mi?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='playground.product', verbose_name='Ait Olduğu Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Rengi ve Stoğu',
                'verbose_name_plural': 'Ürün Renkleri ve Stokları',
                'unique_together': {('product', 'color_name')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Resim')),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='playground.productcolor', verbose_name='Ait Olduğu Renk')),
            ],
            options={
                'verbose_name': 'Ürün Resmi',
                'verbose_name_plural': 'Ürün Resimleri',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Firma Adı')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi Numarası')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sokak ve Numara')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir / İl')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Posta Kodu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
